steps:
  # Step 1: Build the Docker image using Dockerfile-prod
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build'
    args:
      - 'build'
      - '-f'
      - 'Dockerfile-prod'
      - '-t'
      - 'europe-west4-docker.pkg.dev/taskado-477909/taskado-prod/taskado_landing:${SHORT_SHA}'
      - '-t'
      - 'europe-west4-docker.pkg.dev/taskado-477909/taskado-prod/taskado_landing:latest'
      - '--cache-from'
      - 'europe-west4-docker.pkg.dev/taskado-477909/taskado-prod/taskado_landing:latest'
      - '--build-arg'
      - 'BUILDKIT_INLINE_CACHE=1'
      - '.'
    timeout: 1200s

  # Step 2: Push the image with commit hash tag
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-hash'
    args:
      - 'push'
      - 'europe-west4-docker.pkg.dev/taskado-477909/taskado-prod/taskado_landing:${SHORT_SHA}'
    waitFor:
      - 'build'

  # Step 3: Push the image with latest tag
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-latest'
    args:
      - 'push'
      - 'europe-west4-docker.pkg.dev/taskado-477909/taskado-prod/taskado_landing:latest'
    waitFor:
      - 'build'

  # Step 4: Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'deploy-cloudrun'
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image=europe-west4-docker.pkg.dev/taskado-477909/taskado-prod/taskado_landing:${SHORT_SHA}'
      - '--region=${_REGION}'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--port=80'
      - '--max-instances=10'
      - '--min-instances=1'
      - '--cpu=1'
      - '--memory=512Mi'
      - '--timeout=300'
      - '--set-env-vars=NODE_ENV=production'
    waitFor:
      - 'push-hash'
      - 'push-latest'

# Images to be pushed to Artifact Registry
images:
  - 'europe-west4-docker.pkg.dev/taskado-477909/taskado-prod/taskado_landing:${SHORT_SHA}'
  - 'europe-west4-docker.pkg.dev/taskado-477909/taskado-prod/taskado_landing:latest'

# Build options
options:
  machineType: 'N1_HIGHCPU_8'
  diskSizeGb: 100
  logging: CLOUD_LOGGING_ONLY
  
# Timeout for entire build
timeout: 1800s

# Substitutions
substitutions:
  _REGISTRY: 'europe-west4-docker.pkg.dev'
  _PROJECT_ID: 'taskado-477909'
  _REPO: 'taskado-prod'
  _IMAGE: 'taskado_landing'
  _SERVICE_NAME: 'landing-page'
  _REGION: 'europe-west4'

# Tags for organizing builds
tags:
  - 'landing-page'
  - 'production'
  - 'cloud-run'
  - '${SHORT_SHA}'
